set -x
javac com/epi/AddOperatorsinString.java
javac com/epi/AddingCredits.java
javac com/epi/Anagrams.java
javac com/epi/AnonymousLetter.java
javac com/epi/ApproximateSort.java
javac com/epi/Arbitrage.java
javac com/epi/BSTLowestCommonAncestor.java
javac com/epi/BSTSortedOrderTemplate.java
javac com/epi/BSTToSortedDoublyList.java
javac com/epi/BalancedBinaryTreeTemplate.java
javac com/epi/Bentleybsearch.java
javac com/epi/BigNumberMultiplication.java
javac com/epi/BiggestProductNMinus1.java
javac com/epi/BiggestProductNMinus1Math.java
javac com/epi/BinaryOperator.java
javac com/epi/BinarySearchAiEqI.java
javac com/epi/BinarySearchCircularArrayTemplate.java
javac com/epi/BinarySearchCircularArrayWithDuplicatesTemplate.java
javac com/epi/BinarySearchFirstKTemplate.java
javac com/epi/BinarySearchLargerKTemplate.java
javac com/epi/BinarySearchTree.java
javac com/epi/BinarySearchUnknownLengthTemplate.java
javac com/epi/BinaryTreeLevelOrderTemplate.java
javac com/epi/BinaryTreeLockTemplate.java
javac com/epi/BinaryTreePrototypeTemplate.java
javac com/epi/BinaryTreeUtils.java
javac com/epi/BinaryTreeWithParentPrototype.java
javac com/epi/BuildBSTFromSortedArray.java
javac com/epi/CanStringBePalindrome.java
javac com/epi/CanStringBePalindromeHash.java
javac com/epi/CanStringBePalindromeSorting.java
javac com/epi/CelebrityFinding.java
javac com/epi/CheckingCycle.java
javac com/epi/CheckingCycleAlternative.java
javac com/epi/CircularQueueTemplate.java
javac com/epi/CloseSearch.java
javac com/epi/ClosestIntSameBits.java
javac com/epi/ClosestPairPoints.java
javac com/epi/ClosestPalindrome.java
javac com/epi/ClosestStars.java
javac com/epi/ClosestToMedian.java
javac com/epi/CollatzConjecture.java
javac com/epi/CompareKthLargestInHeap.java
javac com/epi/CompletionSearch.java
javac com/epi/ComputingBinomialCoefficients.java
javac com/epi/ComputingXPowN.java
javac com/epi/ConnectLeavesBinaryTreeTemplate.java
javac com/epi/ConvertBase.java
javac com/epi/CopyingPostingsList.java
javac com/epi/CountInversions.java
javac com/epi/Count_occurrences_in_sentence.java
javac com/epi/Counting_sort.java
javac com/epi/DeletionListTemplate.java
javac com/epi/DescendantAndAncestor.java
javac com/epi/Division.java
javac com/epi/Doors.java
javac com/epi/DoublyLinkedListPrototypeTemplate.java
javac com/epi/DrawingSkylines.java
javac com/epi/DutchNationalFlag.java
javac com/epi/EliasCoding.java
javac com/epi/Eliminate_duplicate.java
javac com/epi/EquivClasses.java
javac com/epi/EvenOddMergeLinkedListTemplate.java
javac com/epi/ExteriorBinaryTreeTemplate.java
javac com/epi/FindElementAppearsOnce.java
javac com/epi/FindKLargestBST.java
javac com/epi/FindKthElementInTwoSortedArraysTemplate.java
javac com/epi/FindMissingAndDuplicate.java
javac com/epi/FindMissingAndDuplicateXOR.java
javac com/epi/FindingMinMax.java
javac com/epi/GCD.java
javac com/epi/GassingUp.java
javac com/epi/GaussianElimination.java
javac com/epi/GaussianPrimes.java
javac com/epi/GeneratingABSqrt2.java
javac com/epi/HashDictionary.java
javac com/epi/HeightDetermination.java
javac com/epi/HouseMajority.java
javac com/epi/HuffmanEncoding.java
javac com/epi/ImageCompression.java
javac com/epi/Indirect_sort.java
javac com/epi/InorderTraversalNoStackTemplate.java
javac com/epi/InorderTraversalWithParentTemplate.java
javac com/epi/InterconvertingStringInteger.java
javac com/epi/IntersectRectangle.java
javac com/epi/Intersect_sorted_arrays.java
javac com/epi/Intersect_sorted_arrays1.java
javac com/epi/Intersect_sorted_arrays2.java
javac com/epi/Intersect_sorted_arrays3.java
javac com/epi/IsBinaryTreeABST.java
javac com/epi/IsBinaryTreeABSTConstSpace.java
javac com/epi/JobAssignment.java
javac com/epi/KBalancedBinaryTreeTemplate.java
javac com/epi/KThNodeBinaryTreeTemplate.java
javac com/epi/KthElementStreaming.java
javac com/epi/KthLargestElementLargeN.java
javac com/epi/KthLargestElementTemplate.java
javac com/epi/LRUCache.java
javac com/epi/LargeArray.java
javac com/epi/LargestRectangleUnderSkyline.java
javac com/epi/LazyInit.java
javac com/epi/LevenshteinDistance.java
javac com/epi/LineMostPoints.java
javac com/epi/LinkedListPrototypeTemplate.java
javac com/epi/Linked_list.java
javac com/epi/LoadBalancing.java
javac com/epi/LongestIncreasingSubarray.java
javac com/epi/LongestNondecreasingSubsequenceN2.java
javac com/epi/LongestNondecreasingSubsequenceNlogn.java
javac com/epi/LongestSubarrayK.java
javac com/epi/LowestCommonAncestorHashTemplate.java
javac com/epi/LowestCommonAncestorNoParentTemplate.java
javac com/epi/LowestCommonAncestorTemplate.java
javac com/epi/MatrixRotation.java
javac com/epi/MatrixRotationConstant.java
javac com/epi/MatrixRotationNaive.java
javac com/epi/MatrixSearch.java
javac com/epi/MaxDifferenceKPairs.java
javac com/epi/MaxDifferenceUnlimitedPairs.java
javac com/epi/MaxSubmatrixRectangle.java
javac com/epi/MaxSubmatrixRectangleBruteForce.java
javac com/epi/MaxSubmatrixRectangleImproved.java
javac com/epi/MaxSubmatrixSquare.java
javac com/epi/MaxSumSubarray.java
javac com/epi/MaximumSubarrayInCircularArray.java
javac com/epi/MaximumSubarrayInCircularArrayConstantSpace.java
javac com/epi/MedianSortedCircularLinkedListTemplate.java
javac com/epi/MergeSortedArrays.java
javac com/epi/MergeSortedListsTemplate.java
javac com/epi/MergeTwoBSTs.java
javac com/epi/MinimumDistance3SortedArrays.java
javac com/epi/MinimumSubarrayDifference.java
javac com/epi/MinimumWaitingTime.java
javac com/epi/MissingElement.java
javac com/epi/MultibetCardColorGame.java
javac com/epi/MultiplyShiftAdd.java
javac com/epi/NearestRepetition.java
javac com/epi/NearestRestaurant.java
javac com/epi/NextPermutation.java
javac com/epi/NodeT.java
javac com/epi/NonUniformRandomNumberGeneration.java
javac com/epi/NormalizedPathnames.java
javac com/epi/NumberWays.java
javac com/epi/NumberWaysObstacles.java
javac com/epi/ObjectWrapper.java
javac com/epi/OfflineMinimum.java
javac com/epi/OfflineSampling.java
javac com/epi/OnlineMedian.java
javac com/epi/OnlineSampling.java
javac com/epi/OverlappingListsNoCycle.java
javac com/epi/OverlappingListsTemplate.java
javac com/epi/PaintingIterative.java
javac com/epi/PaintingRecursive.java
javac com/epi/Pair.java
javac com/epi/PalindromeLinkedListTemplate.java
javac com/epi/Parity.java
javac com/epi/Parity1.java
javac com/epi/Parity2.java
javac com/epi/Parity3.java
javac com/epi/Parity4.java
javac com/epi/PermutationArray.java
javac com/epi/PermutationArray1.java
javac com/epi/PermutationArray2.java
javac com/epi/PhoneMnemonic.java
javac com/epi/PickingUpCoins.java
javac com/epi/PickingUpCoinsDontLose.java
javac com/epi/PlanningFishing.java
javac com/epi/Points_covering_intervals.java
javac com/epi/Points_covering_intervals_alternative.java
javac com/epi/PostingsListPrototype.java
javac com/epi/PowerSet.java
javac com/epi/PowerSetAlternative.java
javac com/epi/PrettyPrinting.java
javac com/epi/PrimeSieve.java
javac com/epi/QueueFromStacksTemplate.java
javac com/epi/QueueUsingTwoIntegers.java
javac com/epi/QueueWithMax.java
javac com/epi/QueueWithMaxUsingDeque.java
javac com/epi/RPN.java
javac com/epi/Rearrange.java
javac com/epi/RebuildBSTPostorder.java
javac com/epi/RebuildBSTPreorder.java
javac com/epi/RebuildBSTPreorderBetter.java
javac com/epi/ReconstructBinaryTreePostInOrdersTemplate.java
javac com/epi/ReconstructBinaryTreePreInOrdersTemplate.java
javac com/epi/ReconstructPreorderWithNullTemplate.java
javac com/epi/RegularExpression.java
javac com/epi/RemoveKthLastListTemplate.java
javac com/epi/Rendering_calendar.java
javac com/epi/ReplaceAndRemove.java
javac com/epi/ReservoirSampling.java
javac com/epi/ReverseBits.java
javac com/epi/ReverseLinkedListIterativeTemplate.java
javac com/epi/ReverseLinkedListRecursiveTemplate.java
javac com/epi/ReverseWords.java
javac com/epi/RoadNetwork.java
javac com/epi/RobotBattery.java
javac com/epi/RotateArray.java
javac com/epi/RotateArrayPermutation.java
javac com/epi/RotateArrayTest.java
javac com/epi/RunLengthCompression.java
javac com/epi/ScoreCombination.java
javac com/epi/ScorePermutation.java
javac com/epi/SearchAPairSortedArrayTemplate.java
javac com/epi/SearchBSTFirstLargerK.java
javac com/epi/SearchBSTForFirstOccurrenceIterative.java
javac com/epi/SearchBSTForFirstOccurrenceRecursive.java
javac com/epi/SearchMajority.java
javac com/epi/SearchMaze.java
javac com/epi/SearchMinFirstBST.java
javac com/epi/SearchPostingsListIterative.java
javac com/epi/SearchPostingsListRecursive.java
javac com/epi/Search_frequent_items.java
javac com/epi/ShortestPathFewestEdges.java
javac com/epi/ShortestUniquePrefix.java
javac com/epi/SlidingWindow.java
javac com/epi/SmallestSubarrayCoveringSet.java
javac com/epi/SmallestSubarrayCoveringSetStream.java
javac com/epi/SortedListToBST.java
javac com/epi/SpiralMatrix.java
javac com/epi/SpiralMatrixClockwise.java
javac com/epi/SpreadsheetEncoding.java
javac com/epi/SquareRoot.java
javac com/epi/StableAssignment.java
javac com/epi/StackQueueUsingHeapTemplate.java
javac com/epi/StackSorting.java
javac com/epi/StackWithMaxImproved.java
javac com/epi/StackWithMaxTemplate.java
javac com/epi/StringInMatrix.java
javac com/epi/SubseqCover.java
javac com/epi/Successor.java
javac com/epi/SudokuCheck.java
javac com/epi/SudokuSolve.java
javac com/epi/SwapBits.java
javac com/epi/SymmetricBinaryTreeTemplate.java
javac com/epi/Tail.java
javac com/epi/TailCoin.java
javac com/epi/Task_assignment.java
javac com/epi/TeamPhoto2.java
javac com/epi/Team_photo_1.java
javac com/epi/TheoryOfEquality.java
javac com/epi/ThreeJugs.java
javac com/epi/TiesElection.java
javac com/epi/TournamentTree.java
javac com/epi/TowerHanoi.java
javac com/epi/TransformStringToOther.java
javac com/epi/TransitiveClosure.java
javac com/epi/TreeDiameter.java
javac com/epi/TwoExists.java
javac com/epi/TwoForAll.java
javac com/epi/UniformRandomNumberGeneration.java
javac com/epi/Union_intervals.java
javac com/epi/UpdateBST.java
javac com/epi/Utils.java
javac com/epi/ViewFromAbove.java
javac com/epi/ViewSunset.java
javac com/epi/WiringCircuitBoard.java
javac com/epi/WordBreaking.java
javac com/epi/ZeroOneKnapsack.java
javac com/epi/ZeroSumSubset.java
javac com/epi/ZippingListTemplate.java
javac com/epi/isBinaryTreeABST_BFS.java
javac com/epi/three_sum.java
