set -x
java -ea com.epi.AddOperatorsinString
java -ea com.epi.AddingCredits
java -ea com.epi.Anagrams
java -ea com.epi.AnonymousLetter
java -ea com.epi.ApproximateSort
java -ea com.epi.Arbitrage
java -ea com.epi.BSTLowestCommonAncestor
java -ea com.epi.BSTSortedOrderTemplate
java -ea com.epi.BSTToSortedDoublyList
java -ea com.epi.BalancedBinaryTreeTemplate
java -ea com.epi.Bentleybsearch
java -ea com.epi.BigNumberMultiplication
java -ea com.epi.BiggestProductNMinus1
java -ea com.epi.BiggestProductNMinus1Math
java -ea com.epi.BinaryOperator
java -ea com.epi.BinarySearchAiEqI
java -ea com.epi.BinarySearchCircularArrayTemplate
java -ea com.epi.BinarySearchCircularArrayWithDuplicatesTemplate
java -ea com.epi.BinarySearchFirstKTemplate
java -ea com.epi.BinarySearchLargerKTemplate
java -ea com.epi.BinarySearchTree
java -ea com.epi.BinarySearchUnknownLengthTemplate
java -ea com.epi.BinaryTreeLevelOrderTemplate
java -ea com.epi.BinaryTreeLockTemplate
java -ea com.epi.BinaryTreePrototypeTemplate
java -ea com.epi.BinaryTreeUtils
java -ea com.epi.BinaryTreeWithParentPrototype
java -ea com.epi.BuildBSTFromSortedArray
java -ea com.epi.CanStringBePalindrome
java -ea com.epi.CanStringBePalindromeHash
java -ea com.epi.CanStringBePalindromeSorting
java -ea com.epi.CelebrityFinding
java -ea com.epi.CheckingCycle
java -ea com.epi.CheckingCycleAlternative
java -ea com.epi.CircularQueueTemplate
java -ea com.epi.CloseSearch
java -ea com.epi.ClosestIntSameBits
java -ea com.epi.ClosestPairPoints
java -ea com.epi.ClosestPalindrome
java -ea com.epi.ClosestStars
java -ea com.epi.ClosestToMedian
java -ea com.epi.CollatzConjecture
java -ea com.epi.CompareKthLargestInHeap
java -ea com.epi.CompletionSearch
java -ea com.epi.ComputingBinomialCoefficients
java -ea com.epi.ComputingXPowN
java -ea com.epi.ConnectLeavesBinaryTreeTemplate
java -ea com.epi.ConvertBase
java -ea com.epi.CopyingPostingsList
java -ea com.epi.CountInversions
java -ea com.epi.Count_occurrences_in_sentence
java -ea com.epi.Counting_sort
java -ea com.epi.DeletionListTemplate
java -ea com.epi.DescendantAndAncestor
java -ea com.epi.Division
java -ea com.epi.Doors
java -ea com.epi.DoublyLinkedListPrototypeTemplate
java -ea com.epi.DrawingSkylines
java -ea com.epi.DutchNationalFlag
java -ea com.epi.EliasCoding
java -ea com.epi.Eliminate_duplicate
java -ea com.epi.EquivClasses
java -ea com.epi.EvenOddMergeLinkedListTemplate
java -ea com.epi.ExteriorBinaryTreeTemplate
java -ea com.epi.FindElementAppearsOnce
java -ea com.epi.FindKLargestBST
java -ea com.epi.FindKthElementInTwoSortedArraysTemplate
java -ea com.epi.FindMissingAndDuplicate
java -ea com.epi.FindMissingAndDuplicateXOR
java -ea com.epi.FindingMinMax
java -ea com.epi.GCD
java -ea com.epi.GassingUp
java -ea com.epi.GaussianElimination
java -ea com.epi.GaussianPrimes
java -ea com.epi.GeneratingABSqrt2
java -ea com.epi.HashDictionary
java -ea com.epi.HeightDetermination
java -ea com.epi.HouseMajority
java -ea com.epi.HuffmanEncoding
java -ea com.epi.ImageCompression
java -ea com.epi.Indirect_sort
java -ea com.epi.InorderTraversalNoStackTemplate
java -ea com.epi.InorderTraversalWithParentTemplate
java -ea com.epi.InterconvertingStringInteger
java -ea com.epi.IntersectRectangle
java -ea com.epi.Intersect_sorted_arrays
java -ea com.epi.Intersect_sorted_arrays1
java -ea com.epi.Intersect_sorted_arrays2
java -ea com.epi.Intersect_sorted_arrays3
java -ea com.epi.IsBinaryTreeABST
java -ea com.epi.IsBinaryTreeABSTConstSpace
java -ea com.epi.JobAssignment
java -ea com.epi.KBalancedBinaryTreeTemplate
java -ea com.epi.KThNodeBinaryTreeTemplate
java -ea com.epi.KthElementStreaming
java -ea com.epi.KthLargestElementLargeN
java -ea com.epi.KthLargestElementTemplate
java -ea com.epi.LRUCache
java -ea com.epi.LargeArray
java -ea com.epi.LargestRectangleUnderSkyline
java -ea com.epi.LazyInit
java -ea com.epi.LevenshteinDistance
java -ea com.epi.LineMostPoints
java -ea com.epi.LinkedListPrototypeTemplate
java -ea com.epi.Linked_list
java -ea com.epi.LoadBalancing
java -ea com.epi.LongestIncreasingSubarray
java -ea com.epi.LongestNondecreasingSubsequenceN2
java -ea com.epi.LongestNondecreasingSubsequenceNlogn
java -ea com.epi.LongestSubarrayK
java -ea com.epi.LowestCommonAncestorHashTemplate
java -ea com.epi.LowestCommonAncestorNoParentTemplate
java -ea com.epi.LowestCommonAncestorTemplate
java -ea com.epi.MatrixRotation
java -ea com.epi.MatrixRotationConstant
java -ea com.epi.MatrixRotationNaive
java -ea com.epi.MatrixSearch
java -ea com.epi.MaxDifferenceKPairs
java -ea com.epi.MaxDifferenceUnlimitedPairs
java -ea com.epi.MaxSubmatrixRectangle
java -ea com.epi.MaxSubmatrixRectangleBruteForce
java -ea com.epi.MaxSubmatrixRectangleImproved
java -ea com.epi.MaxSubmatrixSquare
java -ea com.epi.MaxSumSubarray
java -ea com.epi.MaximumSubarrayInCircularArray
java -ea com.epi.MaximumSubarrayInCircularArrayConstantSpace
java -ea com.epi.MedianSortedCircularLinkedListTemplate
java -ea com.epi.MergeSortedArrays
java -ea com.epi.MergeSortedListsTemplate
java -ea com.epi.MergeTwoBSTs
java -ea com.epi.MinimumDistance3SortedArrays
java -ea com.epi.MinimumSubarrayDifference
java -ea com.epi.MinimumWaitingTime
java -ea com.epi.MissingElement
java -ea com.epi.MultibetCardColorGame
java -ea com.epi.MultiplyShiftAdd
java -ea com.epi.NearestRepetition
java -ea com.epi.NearestRestaurant
java -ea com.epi.NextPermutation
java -ea com.epi.NodeT
java -ea com.epi.NonUniformRandomNumberGeneration
java -ea com.epi.NormalizedPathnames
java -ea com.epi.NumberWays
java -ea com.epi.NumberWaysObstacles
java -ea com.epi.ObjectWrapper
java -ea com.epi.OfflineMinimum
java -ea com.epi.OfflineSampling
java -ea com.epi.OnlineMedian
java -ea com.epi.OnlineSampling
java -ea com.epi.OverlappingListsNoCycle
java -ea com.epi.OverlappingListsTemplate
java -ea com.epi.PaintingIterative
java -ea com.epi.PaintingRecursive
java -ea com.epi.Pair
java -ea com.epi.PalindromeLinkedListTemplate
java -ea com.epi.Parity
java -ea com.epi.Parity1
java -ea com.epi.Parity2
java -ea com.epi.Parity3
java -ea com.epi.Parity4
java -ea com.epi.PermutationArray
java -ea com.epi.PermutationArray1
java -ea com.epi.PermutationArray2
java -ea com.epi.PhoneMnemonic
java -ea com.epi.PickingUpCoins
java -ea com.epi.PickingUpCoinsDontLose
java -ea com.epi.PlanningFishing
java -ea com.epi.Points_covering_intervals
java -ea com.epi.Points_covering_intervals_alternative
java -ea com.epi.PostingsListPrototype
java -ea com.epi.PowerSet
java -ea com.epi.PowerSetAlternative
java -ea com.epi.PrettyPrinting
java -ea com.epi.PrimeSieve
java -ea com.epi.QueueFromStacksTemplate
java -ea com.epi.QueueUsingTwoIntegers
java -ea com.epi.QueueWithMax
java -ea com.epi.QueueWithMaxUsingDeque
java -ea com.epi.RPN
java -ea com.epi.Rearrange
java -ea com.epi.RebuildBSTPostorder
java -ea com.epi.RebuildBSTPreorder
java -ea com.epi.RebuildBSTPreorderBetter
java -ea com.epi.ReconstructBinaryTreePostInOrdersTemplate
java -ea com.epi.ReconstructBinaryTreePreInOrdersTemplate
java -ea com.epi.ReconstructPreorderWithNullTemplate
java -ea com.epi.RegularExpression
java -ea com.epi.RemoveKthLastListTemplate
java -ea com.epi.Rendering_calendar
java -ea com.epi.ReplaceAndRemove
java -ea com.epi.ReservoirSampling
java -ea com.epi.ReverseBits
java -ea com.epi.ReverseLinkedListIterativeTemplate
java -ea com.epi.ReverseLinkedListRecursiveTemplate
java -ea com.epi.ReverseWords
java -ea com.epi.RoadNetwork
java -ea com.epi.RobotBattery
java -ea com.epi.RotateArray
java -ea com.epi.RotateArrayPermutation
java -ea com.epi.RotateArrayTest
java -ea com.epi.RunLengthCompression
java -ea com.epi.ScoreCombination
java -ea com.epi.ScorePermutation
java -ea com.epi.SearchAPairSortedArrayTemplate
java -ea com.epi.SearchBSTFirstLargerK
java -ea com.epi.SearchBSTForFirstOccurrenceIterative
java -ea com.epi.SearchBSTForFirstOccurrenceRecursive
java -ea com.epi.SearchMajority
java -ea com.epi.SearchMaze
java -ea com.epi.SearchMinFirstBST
java -ea com.epi.SearchPostingsListIterative
java -ea com.epi.SearchPostingsListRecursive
java -ea com.epi.Search_frequent_items
java -ea com.epi.ShortestPathFewestEdges
java -ea com.epi.ShortestUniquePrefix
java -ea com.epi.SlidingWindow
java -ea com.epi.SmallestSubarrayCoveringSet
java -ea com.epi.SmallestSubarrayCoveringSetStream
java -ea com.epi.SortedListToBST
java -ea com.epi.SpiralMatrix
java -ea com.epi.SpiralMatrixClockwise
java -ea com.epi.SpreadsheetEncoding
java -ea com.epi.SquareRoot
java -ea com.epi.StableAssignment
java -ea com.epi.StackQueueUsingHeapTemplate
java -ea com.epi.StackSorting
java -ea com.epi.StackWithMaxImproved
java -ea com.epi.StackWithMaxTemplate
java -ea com.epi.StringInMatrix
java -ea com.epi.SubseqCover
java -ea com.epi.Successor
java -ea com.epi.SudokuCheck
java -ea com.epi.SudokuSolve
java -ea com.epi.SwapBits
java -ea com.epi.SymmetricBinaryTreeTemplate
java -ea com.epi.Tail
java -ea com.epi.TailCoin
java -ea com.epi.Task_assignment
java -ea com.epi.TeamPhoto2
java -ea com.epi.Team_photo_1
java -ea com.epi.TheoryOfEquality
java -ea com.epi.ThreeJugs
java -ea com.epi.TiesElection
java -ea com.epi.TournamentTree
java -ea com.epi.TowerHanoi
java -ea com.epi.TransformStringToOther
java -ea com.epi.TransitiveClosure
java -ea com.epi.TreeDiameter
java -ea com.epi.TwoExists
java -ea com.epi.TwoForAll
java -ea com.epi.UniformRandomNumberGeneration
java -ea com.epi.Union_intervals
java -ea com.epi.UpdateBST
java -ea com.epi.Utils
java -ea com.epi.ViewFromAbove
java -ea com.epi.ViewSunset
java -ea com.epi.WiringCircuitBoard
java -ea com.epi.WordBreaking
java -ea com.epi.ZeroOneKnapsack
java -ea com.epi.ZeroSumSubset
java -ea com.epi.ZippingListTemplate
java -ea com.epi.isBinaryTreeABST_BFS
java -ea com.epi.three_sum
